import QtQuick 2.5
import QtWebEngine 1.10
import QtWebChannel 1.10
import ".."
import "../js/utils.mjs" as Utils

Item {
    id: webItem
    anchors.fill: parent
    property alias source: web.url
    property bool hasLib: background.hasLib
    property int fps: background.fps
    property var readfile
    property var readWallpaperConfig
    property var getAudio

    onFpsChanged: {
        if(webobj.loaded) {
            webobj.generalProperties.fps = webItem.fps;
            webobj.sigGeneralProperties(webobj.sigGeneralProperties);
        }
    }

    Image {
        id: pauseImage
        anchors.fill: parent
        visible: true
        enabled: false
    }
    QtObject {
        id: webobj
        WebChannel.id: "wpeQml"
        signal sigGeneralProperties(var properties)
        signal sigUserProperties(var properties)
        signal sigAudio(var audioArray)
        property bool loaded: false
        property var userProperties 
        property var generalProperties
        onLoadedChanged: {
            if(!webobj.generalProperties)
                webobj.generalProperties = {fps: 24};
            webobj.sigGeneralProperties(webobj.generalProperties);
            // AI: below section was generated by an AI
            // Read project.json then merge any saved per-wallpaper overrides
            // from read_wallpaper_config before firing sigUserProperties so
            // wallpapers receive their last-saved settings on startup.
            readfile(Common.urlNative(background.getWorkshopIDPath()) + "/project.json", function(text) { 
                const json = Utils.parseJson(text);
                const props = json && json.general && json.general.properties;
                if (!props) return;
                webobj.userProperties = props;
                if (webItem.readWallpaperConfig) {
                    webItem.readWallpaperConfig(background.workshopid).then(function(saved) {
                        if (saved) {
                            for (var key in saved) {
                                if (props[key] !== undefined)
                                    props[key] = Object.assign({}, props[key], { value: saved[key] });
                            }
                        }
                        webobj.sigUserProperties(props);
                    });
                } else {
                    webobj.sigUserProperties(props);
                }
            });
            // AI: end
        }
    }
    WebChannel {
        id: channel
        registeredObjects: [webobj]
    }

    WebEngineView {
    //WebView {
        id: web
        anchors.fill: parent
        enabled: true
        audioMuted: background.mute
        activeFocusOnPress: false
        webChannel: channel

        property bool paused: false
        property bool _init: {
            settings.fullscreenSupportEnabled = true;
            settings.autoLoadIconsForPage = false;
            settings.printElementBackgrounds = false;
            settings.playbackRequiresUserGesture = false;
            settings.pdfViewerEnabled = false;
            settings.showScrollBars = false;

            settings.localContentCanAccessRemoteUrls = true;
            settings.localContentCanAccessFileUrls = true;
            settings.allowGeolocationOnInsecureOrigins = true;
            _init = true;
        }


        //onContextMenuRequested: function(request) {
        //    request.accepted = true;
        //}
        onLoadingChanged: (loadingInfo) => {
            if(loadingInfo.status == WebEngineView.LoadSucceededStatus) {
                // check pause after load
                if(paused) {
                    webItem.play();
                    webItem.pause();
                }
                background.sig_backendFirstFrame('QtWebEngine');
            }
        }
        // AI: below section was generated by an AI
        onJavaScriptConsoleMessage: function(level, message, lineNumber, sourceID) {
            console.log("[WEB] " + message);
        }
        // AI: end

        onPausedChanged: {
            if(paused) {
                pauseTimer.start();
            }
            else {
                web.visible = true;
                web.lifecycleState = WebEngineView.LifecycleState.Active;
                pauseImage.visible = false;
            }
        }

        Component.onCompleted: {
            // Use collection setter with JS dicts (Qt 6 API per WebEngineScriptCollection docs)
            // Enum values: DocumentCreation=2, Deferred=0, MainWorld=0
            userScripts.collection = [
                {
                    name: "QWebChannel",
                    sourceCode: "// Copyright (C) 2016 The Qt Company Ltd.\n// Copyright (C) 2016 Klar\u00e4lvdalens Datakonsult AB, a KDAB Group company, info@kdab.com, author Milian Wolff <milian.wolff@kdab.com>\n// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only\n// Qt-Security score:critical reason:data-parser\n\n\"use strict\";\n\nvar QWebChannelMessageTypes = {\n    signal: 1,\n    propertyUpdate: 2,\n    init: 3,\n    idle: 4,\n    debug: 5,\n    invokeMethod: 6,\n    connectToSignal: 7,\n    disconnectFromSignal: 8,\n    setProperty: 9,\n    response: 10,\n};\n\nvar QWebChannel = function(transport, initCallback, converters)\n{\n    if (typeof transport !== \"object\" || typeof transport.send !== \"function\") {\n        console.error(\"The QWebChannel expects a transport object with a send function and onmessage callback property.\" +\n                      \" Given is: transport: \" + typeof(transport) + \", transport.send: \" + typeof(transport.send));\n        return;\n    }\n\n    var channel = this;\n    this.transport = transport;\n\n    var converterRegistry =\n    {\n        Date : function(response) {\n            if (typeof response === \"string\"\n                && response.match(\n                        /^-?\\d+-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d*)?([-+\\u2212](\\d{2}):(\\d{2})|Z)?$/)) {\n                var date = new Date(response);\n                if (!isNaN(date))\n                    return date;\n            }\n            return undefined; // Return undefined if current converter is not applicable\n        }\n    };\n\n    this.usedConverters = [];\n\n    this.addConverter = function(converter)\n    {\n        if (typeof converter === \"string\") {\n            if (converterRegistry.hasOwnProperty(converter))\n                this.usedConverters.push(converterRegistry[converter]);\n            else\n                console.error(\"Converter '\" + converter + \"' not found\");\n        } else if (typeof converter === \"function\") {\n            this.usedConverters.push(converter);\n        } else {\n            console.error(\"Invalid converter object type \" + typeof converter);\n        }\n    }\n\n    if (Array.isArray(converters)) {\n        for (const converter of converters)\n            this.addConverter(converter);\n    } else if (converters !== undefined) {\n        this.addConverter(converters);\n    }\n\n    this.send = function(data)\n    {\n        if (typeof(data) !== \"string\") {\n            data = JSON.stringify(data);\n        }\n        channel.transport.send(data);\n    }\n\n    this.transport.onmessage = function(message)\n    {\n        var data = message.data;\n        if (typeof data === \"string\") {\n            data = JSON.parse(data);\n        }\n        switch (data.type) {\n            case QWebChannelMessageTypes.signal:\n                channel.handleSignal(data);\n                break;\n            case QWebChannelMessageTypes.response:\n                channel.handleResponse(data);\n                break;\n            case QWebChannelMessageTypes.propertyUpdate:\n                channel.handlePropertyUpdate(data);\n                break;\n            default:\n                console.error(\"invalid message received:\", message.data);\n                break;\n        }\n    }\n\n    this.execCallbacks = {};\n    this.execId = 0;\n    this.exec = function(data, callback)\n    {\n        if (!callback) {\n            // if no callback is given, send directly\n            channel.send(data);\n            return;\n        }\n        if (channel.execId === Number.MAX_VALUE) {\n            // wrap\n            channel.execId = Number.MIN_VALUE;\n        }\n        if (data.hasOwnProperty(\"id\")) {\n            console.error(\"Cannot exec message with property id: \" + JSON.stringify(data));\n            return;\n        }\n        data.id = channel.execId++;\n        channel.execCallbacks[data.id] = callback;\n        channel.send(data);\n    };\n\n    this.objects = {};\n\n    this.handleSignal = function(message)\n    {\n        var object = channel.objects[message.object];\n        if (object) {\n            object.signalEmitted(message.signal, message.args);\n        } else {\n            console.warn(\"Unhandled signal: \" + message.object + \"::\" + message.signal);\n        }\n    }\n\n    this.handleResponse = function(message)\n    {\n        if (!message.hasOwnProperty(\"id\")) {\n            console.error(\"Invalid response message received: \", JSON.stringify(message));\n            return;\n        }\n        channel.execCallbacks[message.id](message.data);\n        delete channel.execCallbacks[message.id];\n    }\n\n    this.handlePropertyUpdate = function(message)\n    {\n        message.data.forEach(data => {\n            var object = channel.objects[data.object];\n            if (object) {\n                object.propertyUpdate(data.signals, data.properties);\n            } else {\n                console.warn(\"Unhandled property update: \" + data.object + \"::\" + data.signal);\n            }\n        });\n        channel.exec({type: QWebChannelMessageTypes.idle});\n    }\n\n    this.debug = function(message)\n    {\n        channel.send({type: QWebChannelMessageTypes.debug, data: message});\n    };\n\n    channel.exec({type: QWebChannelMessageTypes.init}, function(data) {\n        for (const objectName of Object.keys(data)) {\n            new QObject(objectName, data[objectName], channel);\n        }\n\n        // now unwrap properties, which might reference other registered objects\n        for (const objectName of Object.keys(channel.objects)) {\n            channel.objects[objectName].unwrapProperties();\n        }\n\n        if (initCallback) {\n            initCallback(channel);\n        }\n        channel.exec({type: QWebChannelMessageTypes.idle});\n    });\n};\n\nfunction QObject(name, data, webChannel)\n{\n    this.__id__ = name;\n    webChannel.objects[name] = this;\n\n    // List of callbacks that get invoked upon signal emission\n    this.__objectSignals__ = {};\n\n    // Cache of all properties, updated when a notify signal is emitted\n    this.__propertyCache__ = {};\n\n    var object = this;\n\n    // ----------------------------------------------------------------------\n\n    this.unwrapQObject = function(response)\n    {\n        for (const converter of webChannel.usedConverters) {\n            var result = converter(response);\n            if (result !== undefined)\n                return result;\n        }\n\n        if (response instanceof Array) {\n            // support list of objects\n            return response.map(qobj => object.unwrapQObject(qobj))\n        }\n        if (!(response instanceof Object))\n            return response;\n\n        if (!response[\"__QObject*__\"] || response.id === undefined) {\n            var jObj = {};\n            for (const propName of Object.keys(response)) {\n                jObj[propName] = object.unwrapQObject(response[propName]);\n            }\n            return jObj;\n        }\n\n        var objectId = response.id;\n        if (webChannel.objects[objectId])\n            return webChannel.objects[objectId];\n\n        if (!response.data) {\n            console.error(\"Cannot unwrap unknown QObject \" + objectId + \" without data.\");\n            return;\n        }\n\n        var qObject = new QObject( objectId, response.data, webChannel );\n        qObject.destroyed.connect(function() {\n            if (webChannel.objects[objectId] === qObject) {\n                delete webChannel.objects[objectId];\n                // reset the now deleted QObject to an empty {} object\n                // just assigning {} though would not have the desired effect, but the\n                // below also ensures all external references will see the empty map\n                // NOTE: this detour is necessary to workaround QTBUG-40021\n                Object.keys(qObject).forEach(name => delete qObject[name]);\n            }\n        });\n        // here we are already initialized, and thus must directly unwrap the properties\n        qObject.unwrapProperties();\n        return qObject;\n    }\n\n    this.unwrapProperties = function()\n    {\n        for (const propertyIdx of Object.keys(object.__propertyCache__)) {\n            object.__propertyCache__[propertyIdx] = object.unwrapQObject(object.__propertyCache__[propertyIdx]);\n        }\n    }\n\n    function addSignal(signalData, isPropertyNotifySignal)\n    {\n        var signalName = signalData[0];\n        var signalIndex = signalData[1];\n        object[signalName] = {\n            connect: function(callback) {\n                if (typeof(callback) !== \"function\") {\n                    console.error(\"Bad callback given to connect to signal \" + signalName);\n                    return;\n                }\n\n                object.__objectSignals__[signalIndex] = object.__objectSignals__[signalIndex] || [];\n                object.__objectSignals__[signalIndex].push(callback);\n\n                // only required for \"pure\" signals, handled separately for properties in propertyUpdate\n                if (isPropertyNotifySignal)\n                    return;\n\n                // also note that we always get notified about the destroyed signal\n                if (signalName === \"destroyed\" || signalName === \"destroyed()\" || signalName === \"destroyed(QObject*)\")\n                    return;\n\n                // and otherwise we only need to be connected only once\n                if (object.__objectSignals__[signalIndex].length == 1) {\n                    webChannel.exec({\n                        type: QWebChannelMessageTypes.connectToSignal,\n                        object: object.__id__,\n                        signal: signalIndex\n                    });\n                }\n            },\n            disconnect: function(callback) {\n                if (typeof(callback) !== \"function\") {\n                    console.error(\"Bad callback given to disconnect from signal \" + signalName);\n                    return;\n                }\n                // This makes a new list. This is important because it won't interfere with\n                // signal processing if a disconnection happens while emittig a signal\n                object.__objectSignals__[signalIndex] = (object.__objectSignals__[signalIndex] || []).filter(function(c) {\n                  return c != callback;\n                });\n                if (!isPropertyNotifySignal && object.__objectSignals__[signalIndex].length === 0) {\n                    // only required for \"pure\" signals, handled separately for properties in propertyUpdate\n                    webChannel.exec({\n                        type: QWebChannelMessageTypes.disconnectFromSignal,\n                        object: object.__id__,\n                        signal: signalIndex\n                    });\n                }\n            }\n        };\n    }\n\n    /**\n     * Invokes all callbacks for the given signalname. Also works for property notify callbacks.\n     */\n    function invokeSignalCallbacks(signalName, signalArgs)\n    {\n        var connections = object.__objectSignals__[signalName];\n        if (connections) {\n            connections.forEach(function(callback) {\n                callback.apply(callback, signalArgs);\n            });\n        }\n    }\n\n    this.propertyUpdate = function(signals, propertyMap)\n    {\n        // update property cache\n        for (const propertyIndex of Object.keys(propertyMap)) {\n            var propertyValue = propertyMap[propertyIndex];\n            object.__propertyCache__[propertyIndex] = this.unwrapQObject(propertyValue);\n        }\n\n        for (const signalName of Object.keys(signals)) {\n            // Invoke all callbacks, as signalEmitted() does not. This ensures the\n            // property cache is updated before the callbacks are invoked.\n            invokeSignalCallbacks(signalName, signals[signalName]);\n        }\n    }\n\n    this.signalEmitted = function(signalName, signalArgs)\n    {\n        invokeSignalCallbacks(signalName, this.unwrapQObject(signalArgs));\n    }\n\n    function addMethod(methodData)\n    {\n        var methodName = methodData[0];\n        var methodIdx = methodData[1];\n\n        // Fully specified methods are invoked by id, others by name for host-side overload resolution\n        var invokedMethod = methodName[methodName.length - 1] === ')' ? methodIdx : methodName\n\n        object[methodName] = function() {\n            var args = [];\n            var callback;\n            var errCallback;\n            for (var i = 0; i < arguments.length; ++i) {\n                var argument = arguments[i];\n                if (typeof argument === \"function\")\n                    callback = argument;\n                else\n                    args.push(argument);\n            }\n\n            var result;\n            // during test, webChannel.exec synchronously calls the callback\n            // therefore, the promise must be constucted before calling\n            // webChannel.exec to ensure the callback is set up\n            if (!callback && (typeof(Promise) === 'function')) {\n              result = new Promise(function(resolve, reject) {\n                callback = resolve;\n                errCallback = reject;\n              });\n            }\n\n            webChannel.exec({\n                \"type\": QWebChannelMessageTypes.invokeMethod,\n                \"object\": object.__id__,\n                \"method\": invokedMethod,\n                \"args\": args\n            }, function(response) {\n                if (response !== undefined) {\n                    var result = object.unwrapQObject(response);\n                    if (callback) {\n                        (callback)(result);\n                    }\n                } else if (errCallback) {\n                  (errCallback)();\n                }\n            });\n\n            return result;\n        };\n    }\n\n    function bindGetterSetter(propertyInfo)\n    {\n        var propertyIndex = propertyInfo[0];\n        var propertyName = propertyInfo[1];\n        var notifySignalData = propertyInfo[2];\n        // initialize property cache with current value\n        // NOTE: if this is an object, it is not directly unwrapped as it might\n        // reference other QObject that we do not know yet\n        object.__propertyCache__[propertyIndex] = propertyInfo[3];\n\n        if (notifySignalData) {\n            if (notifySignalData[0] === 1) {\n                // signal name is optimized away, reconstruct the actual name\n                notifySignalData[0] = propertyName + \"Changed\";\n            }\n            addSignal(notifySignalData, true);\n        }\n\n        Object.defineProperty(object, propertyName, {\n            configurable: true,\n            get: function () {\n                var propertyValue = object.__propertyCache__[propertyIndex];\n                if (propertyValue === undefined) {\n                    // This shouldn't happen\n                    console.warn(\"Undefined value in property cache for property \\\"\" + propertyName + \"\\\" in object \" + object.__id__);\n                }\n\n                return propertyValue;\n            },\n            set: function(value) {\n                if (value === undefined) {\n                    console.warn(\"Property setter for \" + propertyName + \" called with undefined value!\");\n                    return;\n                }\n                object.__propertyCache__[propertyIndex] = value;\n                var valueToSend = value;\n                webChannel.exec({\n                    \"type\": QWebChannelMessageTypes.setProperty,\n                    \"object\": object.__id__,\n                    \"property\": propertyIndex,\n                    \"value\": valueToSend\n                });\n            }\n        });\n\n    }\n\n    // ----------------------------------------------------------------------\n\n    data.methods.forEach(addMethod);\n\n    data.properties.forEach(bindGetterSetter);\n\n    data.signals.forEach(function(signal) { addSignal(signal, false); });\n\n    Object.assign(object, data.enums);\n}\n\nQObject.prototype.toJSON = function() {\n    if (this.__id__ === undefined) return {};\n    return {\n        id: this.__id__,\n        \"__QObject*__\": true\n    };\n};\n\n//required for use with nodejs\nif (typeof module === 'object') {\n    module.exports = {\n        QWebChannel: QWebChannel\n    };\n}\n",
                    injectionPoint: WebEngineScript.DocumentCreation,
                    worldId: WebEngineScript.MainWorld
                },
                {
                    name: "Audio",
                    sourceCode: "window.wallpaperRegisterAudioListener = function(l) { if(window.wpeQml) window.wpeQml.sigAudio.connect(l); else window.wallpaperRAed = l; };",
                    injectionPoint: WebEngineScript.DocumentCreation,
                    worldId: WebEngineScript.MainWorld
                },
                {
                    name: "ObjectInjector",
                    // AI: below section was generated by an AI
                    // Sets up QWebChannel, wires WE property/audio signals, then directly
                    // fetches project.json via XHR so wallpapers that require
                    // applyUserProperties to init (e.g. AudiOrbits) start correctly.
                    // Status 0 is expected for a successful file:// XHR in Chromium.
                    sourceCode: "new QWebChannel(qt.webChannelTransport, function(ch) { window.wpeQml = ch.objects.wpeQml; var q = window.wpeQml; var pl = window.wallpaperPropertyListener; console.log('WPE: ObjectInjector connected pl=' + (pl ? 'yes' : 'no')); if(window.wallpaperRAed) q.sigAudio.connect(window.wallpaperRAed); if(pl) { if(pl.applyGeneralProperties) q.sigGeneralProperties.connect(pl.applyGeneralProperties); if(pl.applyUserProperties) q.sigUserProperties.connect(pl.applyUserProperties); } q.loaded = true; if(pl && pl.applyUserProperties) { var xhr = new XMLHttpRequest(); xhr.open('GET', './project.json', true); xhr.onreadystatechange = function() { if(xhr.readyState === 4 && (xhr.status === 0 || xhr.status === 200)) { try { var proj = JSON.parse(xhr.responseText); var props = proj && proj.general && proj.general.properties; if(props) { console.log('WPE: XHR applyUserProperties ok (' + Object.keys(props).length + ' props) webgl=' + (!!window.WebGLRenderingContext) + ' expwebgl=' + (function(){try{return !!document.createElement(String.fromCharCode(99,97,110,118,97,115)).getContext('webgl');}catch(e){return false;}}())); if(props.seizure_warning) props.seizure_warning.value = false; if(pl.applyGeneralProperties) pl.applyGeneralProperties({fps: 30}); pl.applyUserProperties(props); setTimeout(function(){ var ao=window.audiOrbits; console.log('WPE: post-init state=' + (ao?ao.state:'no-audiOrbits') + ' renderer=' + (ao&&ao.renderer?'yes':'no') + ' THREE=' + (typeof THREE) + ' Detector.webgl=' + (typeof Detector!=='undefined'?Detector.webgl:'no-Detector')); }, 2000); } } catch(e) { console.warn('WPE: project.json error: ' + e); } } }; xhr.send(); } var _origErr=window.onerror; window.onerror=function(msg,src,line,col,err){ console.log('WPE: window.onerror: '+msg+' @ '+src+':'+line); if(_origErr) _origErr(msg,src,line,col,err); return false; }; document.getElementsByTagName('body')[0].ondragstart = function() { return false; }; });",
                    // AI: end
                    injectionPoint: WebEngineScript.Deferred,
                    worldId: WebEngineScript.MainWorld
                }
            ];
            background.nowBackend = 'QtWebEngine';
        }

    }
    // There is no signal for frame complete, so use timer to make sure not black result
    Timer{
        id: pauseTimer
        running: false
        repeat: false
        interval: 300 
        onTriggered: {
            // only check paused status on timer, not set
            // this is async
            web.grabToImage(function(result) {
                // check for paused again, make sure web is visible
                if(web.paused == false || web.visible == false) return;
                pauseImage.source = result.url;
                pauseImage.visible = true;
                web.visible = false;
                web.lifecycleState = WebEngineView.LifecycleState.Frozen;
            });
        }   
    }
    // AI: below section was generated by an AI
    // Poll Python audio helper at ~30 fps and forward FFT data to the
    // QWebChannel object so web wallpapers receive it via
    // window.wallpaperRegisterAudioListener.
    Timer {
        id: audioTimer
        interval: 33
        running: webItem.getAudio !== undefined && webobj.loaded
        repeat: true
        onTriggered: {
            webItem.getAudio().then(function(data) {
                if (data && data.length > 0)
                    webobj.sigAudio(data);
            });
        }
    }
    // AI: end

    Component.onCompleted: {
    //target: web.children[0] ? web.children[0] : null
    }

    function play(){
        web.paused = false;
    }
    function pause(){
        // Set status first
        web.paused = true;
    }
    function getMouseTarget() {
        web.activeFocusOnPress = true;
        return Qt.binding(function() { return web.children[0]; })
    }
}
