#!/bin/python3

import asyncio
import websockets
import json
import base64
import math
import os
import platform
import shutil

from pathlib import Path

from typing import Callable,Any,Optional

# AI: below section was generated by an AI
# Audio capture: reads PCM from parec (PipeWire/PulseAudio monitor), computes
# a 64-bin FFT magnitude spectrum mirrored to stereo 128-bin array [L|R],
# stores the result in _audio_data so get_audio() can return it synchronously.
try:
    import numpy as _np
    _NUMPY_OK = True
except ImportError:
    _NUMPY_OK = False

_audio_data: list = [0.0] * 128
_audio_proc = None
_run_max: float = 1.0

async def _find_monitor_source() -> str:
    """Return the best PulseAudio/PipeWire monitor source name.
    Prefers the default source if it is a monitor, then any IDLE/RUNNING
    monitor, then any monitor at all. Falls back to '' (parec default)."""
    try:
        # Check default source first — if it's already a monitor, use it
        def_proc = await asyncio.create_subprocess_exec(
            'pactl', 'get-default-source',
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        def_out, _ = await def_proc.communicate()
        default = def_out.decode().strip()
        if '.monitor' in default:
            return default

        # Otherwise scan sources, preferring non-SUSPENDED ones
        list_proc = await asyncio.create_subprocess_exec(
            'pactl', 'list', 'short', 'sources',
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.DEVNULL,
        )
        list_out, _ = await list_proc.communicate()
        active = ''
        fallback = ''
        for line in list_out.decode().splitlines():
            parts = line.split()
            if len(parts) < 2 or '.monitor' not in parts[1]:
                continue
            state = parts[4] if len(parts) >= 5 else ''
            if state in ('IDLE', 'RUNNING'):
                if not active:
                    active = parts[1]
            elif not fallback:
                fallback = parts[1]
        return active or fallback
    except Exception:
        pass
    return ''  # empty → parec uses the default source

async def _audio_capture_loop() -> None:
    """Continuously read float32 mono PCM from parec and update _audio_data.
    Auto-detects the best monitor source on each (re)start so it survives reboots."""
    global _audio_data, _audio_proc, _run_max
    RATE  = 44100
    CHUNK = 1024
    BINS  = 64   # 64 bins per channel; output is [L0..L63, R0..R63]
    DECAY = 0.995  # running-max decay ≈ 3 s to baseline at 30 fps

    while True:  # restart loop — recovers if parec exits
        try:
            source = await _find_monitor_source()
            cmd = [
                'parec',
                '--format=float32le',
                f'--rate={RATE}',
                '--channels=1',
                '--latency-msec=30',
            ]
            if source:
                cmd += ['--device', source]
            _audio_proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.DEVNULL,
            )
            bytes_per_frame = CHUNK * 4  # float32
            buf = b''
            while True:
                chunk = await _audio_proc.stdout.read(bytes_per_frame)
                if not chunk:
                    break
                buf += chunk
                while len(buf) >= bytes_per_frame:
                    frame, buf = buf[:bytes_per_frame], buf[bytes_per_frame:]
                    samples = _np.frombuffer(frame, dtype=_np.float32)
                    windowed = samples * _np.hanning(CHUNK)
                    mag = _np.abs(_np.fft.rfft(windowed, n=CHUNK))[:BINS].astype(float)
                    frame_max = float(_np.max(mag)) if mag.size else 0.0
                    _run_max = max(_run_max * DECAY, frame_max, 1e-6)
                    scaled = (mag / _run_max).tolist()
                    _audio_data = scaled + scaled  # mirror mono → stereo [L|R]
        except Exception:
            pass
        await asyncio.sleep(2)  # wait before retrying

# AI: end

# import functools;



class Main:
    def __init__(self):
        self.config_dir: Path = self.__config_dir()
        self.config_wallpaper_dir: Path = self.config_dir / 'wallpaper'

        self.config_wallpaper_dir.mkdir(parents=True, exist_ok=True)

    def __config_dir(self) -> Path:
        config_name: str = "wekde"
        xdg_config_home: Optional[str] = os.getenv("XDG_CONFIG_HOME")
        if xdg_config_home:
            return Path(xdg_config_home) / config_name
        return Path.home() / ".config" / config_name
    def __wallpaper_config_file(self, id: str) -> Path:
        return self.config_wallpaper_dir / (id + '.json')

    def read_wallpaper_config(self, id: str) -> dict:
        cfg_file: Path = self.__wallpaper_config_file(id)
        if not cfg_file.exists():
            return dict()

        with open(cfg_file, "r") as f:
            return json.load(f)

    def write_wallpaper_config(self, id: str, changed: dict) -> None:
        cfg: dict = self.read_wallpaper_config(id)
        cfg.update(changed)
        cfg_file: Path = self.__wallpaper_config_file(id)

        with open(cfg_file, "w+") as f:
            json.dump(cfg, f)

    def reset_wallpaper_config(self, id: str) -> None:
        cfg_file: Path = self.__wallpaper_config_file(id)
        cfg_file.unlink()

    def delete_wallpaper_config(self, id: str) -> None:
        cfg_file: Path = self.__wallpaper_config_file(id)
        if cfg_file.exists():
            cfg_file.unlink()

class Jsonrpc:
    def __init__(self):
        self.method_map = dict()

    def add_method(self, func: Callable) -> Callable:
        self.method_map[func.__name__] = func
        return func

    def add_class_method(self, obj: Any, func: Callable) -> None:
        def wrapper(*args):
            func(obj, *args)
        self.method_map[func.__name__] = wrapper

    def handle(self, msg) -> str:
        j: dict = {}
        error = None
        try:
            j = json.loads(msg)
        except Exception as e:
            error = repr(e)
            return json.dumps({"id": -1, "error": error})

        result = {"id": j.get("id")}
        method = j.get("method")
        if method in self.method_map:
            func = self.method_map[method]
            params = j.get("params") or []
            try:
                result["result"] = func(*params)
            except Exception as e:
                error = repr(e)
        else:
            error = "jsonrpc no such func"
        if error:
            result["error"] = error
        return json.dumps(result)

M = Main()
jrpc = Jsonrpc()


@jrpc.add_method
def version() -> str:
    return platform.python_version()


@jrpc.add_method
def readfile(path: str) -> str:
    with open(path, "rb") as f:
        data: bytes = f.read()
        return base64.b64encode(data).decode("ascii")


@jrpc.add_method
def get_dir_size(path: str, depth: int) -> int:
    glob_strs: list[str] = (
        ["**/*"]
        if depth <= 0
        else ["/".join(["*" for _ in range(i + 1)]) for i in range(depth)]
    )
    root_directory: Path = Path(path)
    return sum(
        [
            sum(f.stat().st_size for f in root_directory.glob(s) if f.is_file())
            for s in glob_strs
        ]
    )


@jrpc.add_method
def get_folder_list(path: str, _opt: dict = {}) -> Optional[dict]:
    def gen_item(f: Path) -> dict:
        stat: os.stat_result = f.stat()
        return {"name": f.name, "mtime": math.floor(stat.st_mtime)}

    opt: dict = get_folder_list.default_opt.copy()
    opt.update(_opt)
    opt_only_dir = opt["only_dir"]

    def path_filter(p: Path) -> bool:
        return p.is_dir() if opt_only_dir else True

    folder: Optional[Path] = next(
        filter(lambda p: p.is_dir(), [Path(p) for p in [path, *opt["fallbacks"]]]), None
    )
    if folder is None:
        return None
    return {
        "folder": str(folder),
        "items": [gen_item(p) for p in folder.glob("*") if path_filter(p)],
    }
get_folder_list.default_opt = {"only_dir": True, "fallbacks": []}

jrpc.add_method(M.read_wallpaper_config)
jrpc.add_method(M.write_wallpaper_config)
jrpc.add_method(M.reset_wallpaper_config)

@jrpc.add_method
def get_audio() -> list:
    """Return the latest 128-bin FFT spectrum as floats in [0, 1]."""
    return _audio_data


@jrpc.add_method
def delete_wallpaper(path: str, workshopid: str = "") -> dict:
    # Safety: require the target to be an existing directory containing
    # a project.json file so arbitrary paths can't be wiped out.
    try:
        folder: Path = Path(path).resolve()
        if not folder.is_dir():
            return {"ok": False, "error": "not a directory"}
        if not (folder / "project.json").is_file():
            return {"ok": False, "error": "not a wallpaper folder"}
        shutil.rmtree(folder)
        if workshopid:
            M.delete_wallpaper_config(workshopid)
        return {"ok": True}
    except Exception as e:
        return {"ok": False, "error": repr(e)}


async def connect(uri):
    async with websockets.connect(uri) as websocket:
        while True:
            recv: str = jrpc.handle(await websocket.recv())
            await websocket.send(recv)

async def _main(uri: str) -> None:
    if _NUMPY_OK:
        asyncio.create_task(_audio_capture_loop())
    await connect(uri)

if __name__ == "__main__":
    import argparse

    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description="qml localfile helper"
    )
    parser.add_argument("url", metavar="URL", type=str, help="a websocket url")
    args: dict = vars(parser.parse_args())

    if hasattr(asyncio, "run"):
        asyncio.run(_main(args["url"]))
    else:
        asyncio.get_event_loop().run_until_complete(_main(args["url"]))
